import { neon } from '@neondatabase/serverless';
import crypto from 'crypto';
const sql=process.env.DATABASE_URL?neon(process.env.DATABASE_URL):null;
const SECRET=process.env.AUTH_SECRET||'SMART_ATTENDANCE_DEV_SECRET_CHANGE_ME';
if(!process.env.AUTH_SECRET) console.warn('AUTH_SECRET is not configured; set a strong value in Vercel for production.');
const DEFAULT_LECTURES=[['1','Data Structures','09:00','10:00'],['2','Operating Systems','10:00','11:00'],['3','DBMS','11:15','12:15'],['4','Computer Networks','12:15','13:15'],['5','Python','14:00','15:00'],['6','AI & ML','15:00','16:00'],['7','Web Technology','16:00','17:00'],['8','Project','17:00','18:00']];
const AUTO_HOLIDAYS={'2026-01-26':'Republic Day','2026-03-04':'Holi','2026-03-21':'Id-ul-Fitr','2026-03-26':'Ram Navami','2026-03-31':'Mahavir Jayanti','2026-04-03':'Good Friday','2026-05-01':'Buddha Purnima','2026-05-27':'Id-ul-Zuha (Bakrid)','2026-06-26':'Muharram','2026-08-15':'Independence Day','2026-08-26':'Milad-un-Nabi / Id-e-Milad','2026-09-04':'Janmashtami','2026-10-02':'Mahatma Gandhi Jayanti','2026-10-20':'Dussehra (Vijay Dashami)','2026-11-08':'Diwali (Deepavali)','2026-11-24':"Guru Nanak's Birthday",'2026-12-25':'Christmas Day'};
const hash=p=>crypto.createHash('sha256').update(String(p||'')).digest('hex');
const b64=o=>Buffer.from(JSON.stringify(o)).toString('base64url');
const sign=x=>crypto.createHmac('sha256',SECRET).update(x).digest('base64url');
function token(user,role){const x=b64({u:user,r:role,iat:Date.now()});return x+'.'+sign(x)}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;const t=h.slice(7).split('.');if(t.length!==2||sign(t[0])!==t[1])return null;try{const p=JSON.parse(Buffer.from(t[0],'base64url').toString());if(Date.now()-p.iat>12*60*60*1000)return null;return{username:p.u,role:p.r}}catch{return null}}
function allow(user,roles){if(!user)return false;return roles.includes(user.role)}
function today(){return new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'})}
function holidayFor(d){const x=new Date(d+'T00:00:00+05:30');if(x.getDay()===0)return{is_holiday:true,name:'Sunday',type:'Automatic'};if(AUTO_HOLIDAYS[d])return{is_holiday:true,name:AUTO_HOLIDAYS[d],type:'Official/Gazetted'};return{is_holiday:false,name:'',type:''}}
async function seed(){await sql`CREATE TABLE IF NOT EXISTS students(student_id TEXT PRIMARY KEY,name TEXT NOT NULL,roll_no TEXT,course TEXT,semester TEXT,section TEXT,parent_mobile TEXT,parent_email TEXT,face_descriptor JSONB,created_at TIMESTAMPTZ DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS timetable(lecture_no INTEGER PRIMARY KEY,subject TEXT NOT NULL,start_time TEXT NOT NULL,end_time TEXT NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS attendance(student_id TEXT NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,attendance_date DATE NOT NULL,lecture_no INTEGER NOT NULL,lecture_start TEXT,lecture_end TEXT,in_time TEXT,out_time TEXT,status TEXT,PRIMARY KEY(student_id,attendance_date,lecture_no))`;await sql`CREATE TABLE IF NOT EXISTS movement(id BIGSERIAL PRIMARY KEY,student_id TEXT NOT NULL REFERENCES students(student_id) ON DELETE CASCADE,attendance_date DATE NOT NULL,lecture_no INTEGER NOT NULL,movement_type TEXT NOT NULL,event_time TEXT NOT NULL,reason TEXT)`;await sql`CREATE TABLE IF NOT EXISTS user_accounts(username TEXT PRIMARY KEY,role TEXT NOT NULL,password_hash TEXT NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS audit_log(id BIGSERIAL PRIMARY KEY,username TEXT,role TEXT,action TEXT,details TEXT,event_time TIMESTAMPTZ DEFAULT now())`;await sql`CREATE TABLE IF NOT EXISTS holidays(holiday_date DATE PRIMARY KEY,name TEXT NOT NULL,holiday_type TEXT NOT NULL)`;await sql`CREATE TABLE IF NOT EXISTS notifications(id BIGSERIAL PRIMARY KEY,student_id TEXT,student_name TEXT,channel TEXT,recipient TEXT,subject TEXT,message TEXT,status TEXT,details TEXT,sent_at TIMESTAMPTZ DEFAULT now())`;const n=await sql`SELECT COUNT(*)::int c FROM timetable`;if(!n[0].c)for(const l of DEFAULT_LECTURES)await sql`INSERT INTO timetable(lecture_no,subject,start_time,end_time) VALUES(${+l[0]},${l[1]},${l[2]},${l[3]}) ON CONFLICT(lecture_no) DO NOTHING`;const u=await sql`SELECT username FROM user_accounts`;if(!u.length){await sql`INSERT INTO user_accounts(username,role,password_hash) VALUES('admin','Admin',${hash(process.env.ADMIN_PASSWORD||'admin123')}),('teacher','Teacher',${hash(process.env.TEACHER_PASSWORD||'teacher123')}),('viewer','Viewer','')`}}
async function finalize(){const d=today(),ts=new Date().toLocaleTimeString('en-GB',{hour12:false,timeZone:'Asia/Kolkata'});const rows=await sql`SELECT lecture_no,end_time FROM timetable`;for(const l of rows){if(ts>=String(l.end_time)+':00')await sql`UPDATE attendance SET out_time=${l.end_time} WHERE attendance_date=${d} AND lecture_no=${l.lecture_no} AND coalesce(in_time,'')<>'' AND coalesce(out_time,'')=''`}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(!sql)return res.status(503).json({ok:false,error:'DATABASE_URL is not configured'});const u=new URL(req.url,'http://localhost');const r=u.searchParams.get('resource');try{await seed();
if(r==='health'&&req.method==='GET')return res.json({ok:true,service:'Smart Attendance API',database:true});
if(r==='login'&&req.method==='POST'){const {username,password=''}=req.body||{};const rows=await sql`SELECT username,role,password_hash FROM user_accounts WHERE lower(username)=lower(${String(username||'')})`;if(!rows.length)return res.status(401).json({ok:false,error:'Invalid username'});const a=rows[0];const good=a.role==='Viewer'?String(password)==='':a.password_hash===hash(password);if(!good)return res.status(401).json({ok:false,error:'Invalid password'});await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${a.username},${a.role},'LOGIN','Web login')`;return res.json({ok:true,username:a.username,role:a.role,token:token(a.username,a.role)})}
const user=auth(req);if(!user)return res.status(401).json({ok:false,error:'Login required'});
if(r==='bootstrap'&&req.method==='GET'){await finalize();const [students,timetable,attendance,movement,holidays,notifications]=await Promise.all([sql`SELECT student_id,name,roll_no,course,semester,section,parent_mobile,parent_email,face_descriptor FROM students ORDER BY student_id`,sql`SELECT lecture_no,subject,start_time,end_time FROM timetable ORDER BY lecture_no`,sql`SELECT a.*,s.name FROM attendance a LEFT JOIN students s ON s.student_id=a.student_id ORDER BY attendance_date DESC,lecture_no,student_id`,sql`SELECT m.*,s.name FROM movement m LEFT JOIN students s ON s.student_id=m.student_id ORDER BY id DESC LIMIT 500`,sql`SELECT holiday_date,name,holiday_type FROM holidays ORDER BY holiday_date`,sql`SELECT * FROM notifications ORDER BY id DESC LIMIT 500`]);return res.json({user,students,timetable,attendance,movement,holidays,notifications})}
if(r==='students'&&req.method==='POST'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const s=req.body||{};await sql`INSERT INTO students(student_id,name,roll_no,course,semester,section,parent_mobile,parent_email,face_descriptor) VALUES(${s.student_id},${s.name},${s.roll_no||''},${s.course||''},${s.semester||''},${s.section||''},${s.parent_mobile||''},${s.parent_email||''},${s.face_descriptor?JSON.stringify(s.face_descriptor):null}) ON CONFLICT(student_id) DO UPDATE SET name=excluded.name,roll_no=excluded.roll_no,course=excluded.course,semester=excluded.semester,section=excluded.section,parent_mobile=excluded.parent_mobile,parent_email=excluded.parent_email,face_descriptor=COALESCE(excluded.face_descriptor,students.face_descriptor)`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'STUDENT_SAVE',${s.student_id})`;return res.json({ok:true})}
if(r==='students'&&req.method==='DELETE'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const id=u.searchParams.get('id');await sql`DELETE FROM students WHERE student_id=${id}`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'STUDENT_DELETE',${id})`;return res.json({ok:true})}
if(r==='attendance'&&req.method==='POST'){if(!allow(user,['Admin','Teacher']))return res.status(403).json({ok:false,error:'Teacher or Admin only'});const a=req.body||{},d=a.attendance_date||today();if(holidayFor(d).is_holiday)return res.status(403).json({ok:false,error:'Attendance disabled on holiday: '+holidayFor(d).name});if(a.action==='in'){const dup=await sql`SELECT 1 FROM attendance WHERE student_id=${a.student_id} AND attendance_date=${d} AND lecture_no=${+a.lecture_no}`;if(dup.length)return res.status(409).json({ok:false,error:'Duplicate attendance: IN already recorded for this student and lecture'});await sql`INSERT INTO attendance(student_id,attendance_date,lecture_no,lecture_start,lecture_end,in_time,out_time,status) VALUES(${a.student_id},${d},${+a.lecture_no},${a.lecture_start},${a.lecture_end},${a.in_time},'',${a.status})`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'ATTENDANCE_IN',${a.student_id+' L'+a.lecture_no})`;return res.json({ok:true})}if(a.action==='final_out'){await sql`UPDATE attendance SET out_time=${a.lecture_end} WHERE student_id=${a.student_id} AND attendance_date=${d} AND lecture_no=${+a.lecture_no} AND coalesce(in_time,'')<>'' AND coalesce(out_time,'')=''`;return res.json({ok:true})}if(a.action==='finalize_lecture'){await sql`UPDATE attendance SET out_time=${a.lecture_end} WHERE attendance_date=${d} AND lecture_no=${+a.lecture_no} AND coalesce(in_time,'')<>'' AND coalesce(out_time,'')=''`;return res.json({ok:true})}}
if(r==='movement'&&req.method==='POST'){if(!allow(user,['Admin','Teacher']))return res.status(403).json({ok:false,error:'Teacher or Admin only'});const m=req.body||{};const d=m.attendance_date||today();if(holidayFor(d).is_holiday)return res.status(403).json({ok:false,error:'Movement disabled on holiday'});const last=await sql`SELECT movement_type FROM movement WHERE student_id=${m.student_id} AND attendance_date=${d} AND lecture_no=${+m.lecture_no} ORDER BY id DESC LIMIT 1`;const current=last[0]?.movement_type||'IN';if(m.movement_type==='OUT'&&current==='OUT')return res.status(409).json({ok:false,error:'Student is already TEMP OUT'});if(m.movement_type==='IN'&&current!=='OUT')return res.status(409).json({ok:false,error:'Student is not TEMP OUT'});await sql`INSERT INTO movement(student_id,attendance_date,lecture_no,movement_type,event_time,reason) VALUES(${m.student_id},${d},${+m.lecture_no},${m.movement_type},${m.event_time},${m.reason||''})`;return res.json({ok:true})}
if(r==='holiday'&&req.method==='POST'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const h=req.body||{};await sql`INSERT INTO holidays(holiday_date,name,holiday_type) VALUES(${h.holiday_date},${h.name},'College Custom') ON CONFLICT(holiday_date) DO UPDATE SET name=excluded.name,holiday_type='College Custom'`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'HOLIDAY_ADD',${h.holiday_date+' '+h.name})`;return res.json({ok:true})}
if(r==='holiday'&&req.method==='DELETE'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const d=u.searchParams.get('date');await sql`DELETE FROM holidays WHERE holiday_date=${d} AND holiday_type='College Custom'`;return res.json({ok:true})}
if(r==='timetable'&&req.method==='POST'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const t=req.body||{};await sql`INSERT INTO timetable(lecture_no,subject,start_time,end_time) VALUES(${+t.lecture_no},${t.subject},${t.start_time},${t.end_time}) ON CONFLICT(lecture_no) DO UPDATE SET subject=excluded.subject,start_time=excluded.start_time,end_time=excluded.end_time`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'TIMETABLE_SAVE',${'L'+t.lecture_no})`;return res.json({ok:true})}
if(r==='notifications'&&req.method==='POST'){if(!allow(user,['Admin','Teacher']))return res.status(403).json({ok:false,error:'Teacher or Admin only'});const n=req.body||{};await sql`INSERT INTO notifications(student_id,student_name,channel,recipient,subject,message,status,details) VALUES(${n.student_id},${n.student_name},${n.channel},${n.recipient||''},${n.subject||''},${n.message||''},'Queued','Web queue')`;return res.json({ok:true})}
if(r==='password'&&req.method==='POST'){if(!allow(user,['Admin','Teacher']))return res.status(403).json({ok:false,error:'Viewer has no password and cannot change one'});const b=req.body||{},oldp=String(b.old_password||''),newp=String(b.new_password||'');if(newp.length<4)return res.status(400).json({ok:false,error:'New password must be at least 4 characters'});const rows=await sql`SELECT password_hash FROM user_accounts WHERE username=${user.username} AND role=${user.role}`;if(!rows.length||rows[0].password_hash!==hash(oldp))return res.status(401).json({ok:false,error:'Current password is incorrect'});await sql`UPDATE user_accounts SET password_hash=${hash(newp)} WHERE username=${user.username}`;await sql`INSERT INTO audit_log(username,role,action,details) VALUES(${user.username},${user.role},'PASSWORD_CHANGE','Own password changed')`;return res.json({ok:true})}
if(r==='audit'&&req.method==='GET'){if(!allow(user,['Admin']))return res.status(403).json({ok:false,error:'Admin only'});const rows=await sql`SELECT event_time,username,role,action,details FROM audit_log ORDER BY id DESC LIMIT 500`;return res.json({ok:true,rows})}
return res.status(404).json({ok:false,error:'Unknown resource'});
}catch(e){console.error(e);return res.status(500).json({ok:false,error:e.message})}}
